export const THEME_VARS = {
  light: {
    bg: "bg-[#fafafa]",
    text: "text-[#1a1a1a]",
    headerBg: "bg-[#fafafa]/80 border-[#e0e0e0]",
    panelBg: "bg-[#fafafa] border-[#e0e0e0]",
    cardBg: "bg-white border-[#e0e0e0]",
    inputBg: "bg-[#f5f5f5] border-[#e0e0e0]",
    mutedText: "text-[#555555]",
    mutedText2: "text-[#888888]",
    hoverBorder: "hover:border-[#cccccc]",
    activeBtn: "bg-[#fff0f0] border-[#e0d0d0] text-[#c53a3a]",
    inactiveBtn: "bg-white border-[#e0e0e0] text-[#555555] hover:text-[#1a1a1a] hover:border-[#cccccc]",
    codeBg: "bg-[#f5f5f5] border-[#e0e0e0]",
  },
  dark: {
    bg: "bg-[#050505]",
    text: "text-[#c8c8c8]",
    headerBg: "bg-[#050505]/80 border-[#1a1a1a]",
    panelBg: "bg-[#0a0a0a] border-[#1a1a1a]",
    cardBg: "bg-[#0a0a0a] border-[#1a1a1a]",
    inputBg: "bg-[#050505] border-[#1a1a1a]",
    mutedText: "text-[#555555]",
    mutedText2: "text-[#555555]",
    hoverBorder: "hover:border-[#2a2a2a]",
    activeBtn: "bg-[rgba(255,107,107,0.08)] border-[rgba(255,107,107,0.2)] text-[#FF6B6B]",
    inactiveBtn: "bg-[#0a0a0a] border-[#1a1a1a] text-[#555555] hover:text-[#888888] hover:border-[#2a2a2a]",
    codeBg: "bg-[#0a0a0a] border-[#1a1a1a]",
  },
};

export const DATA_TYPE_PRESETS = {
  users: [
    { id: "1", name: "id", type: "uuid" },
    { id: "2", name: "first_name", type: "fullName" },
    { id: "3", name: "last_name", type: "fullName" },
    { id: "4", name: "email", type: "email" },
    { id: "5", name: "age", type: "amount" },
    { id: "6", name: "phone", type: "phone" },
    { id: "7", name: "city", type: "fullName" },
    { id: "8", name: "state", type: "fullName" },
    { id: "9", name: "created_at", type: "email" },
  ],
  products: [
    { id: "1", name: "id", type: "uuid" },
    { id: "2", name: "title", type: "fullName" },
    { id: "3", name: "price", type: "amount" },
    { id: "4", name: "in_stock", type: "boolean" },
    { id: "5", name: "company", type: "company" },
  ],
  orders: [
    { id: "1", name: "id", type: "uuid" },
    { id: "2", name: "customer", type: "fullName" },
    { id: "3", name: "email", type: "email" },
    { id: "4", name: "amount", type: "amount" },
    { id: "5", name: "status", type: "boolean" },
  ],
  addresses: [
    { id: "1", name: "id", type: "uuid" },
    { id: "2", name: "full_name", type: "fullName" },
    { id: "3", name: "street", type: "fullName" },
    { id: "4", name: "city", type: "fullName" },
    { id: "5", name: "state", type: "fullName" },
    { id: "6", name: "phone", type: "phone" },
  ],
  transactions: [
    { id: "1", name: "id", type: "uuid" },
    { id: "2", name: "amount", type: "amount" },
    { id: "3", name: "currency", type: "fullName" },
    { id: "4", name: "status", type: "boolean" },
    { id: "5", name: "description", type: "jobTitle" },
    { id: "6", name: "created_at", type: "email" },
  ],
  posts: [
    { id: "1", name: "id", type: "uuid" },
    { id: "2", name: "title", type: "jobTitle" },
    { id: "3", name: "author", type: "fullName" },
    { id: "4", name: "email", type: "email" },
    { id: "5", name: "likes", type: "amount" },
    { id: "6", name: "published", type: "boolean" },
  ],
  employees: [
    { id: "1", name: "id", type: "uuid" },
    { id: "2", name: "full_name", type: "fullName" },
    { id: "3", name: "email", type: "email" },
    { id: "4", name: "job_title", type: "jobTitle" },
    { id: "5", name: "company", type: "company" },
    { id: "6", name: "phone", type: "phone" },
    { id: "7", name: "salary", type: "amount" },
  ],
  invoices: [
    { id: "1", name: "id", type: "uuid" },
    { id: "2", name: "customer", type: "fullName" },
    { id: "3", name: "email", type: "email" },
    { id: "4", name: "amount", type: "amount" },
    { id: "5", name: "company", type: "company" },
    { id: "6", name: "paid", type: "boolean" },
  ],
  reviews: [
    { id: "1", name: "id", type: "uuid" },
    { id: "2", name: "reviewer", type: "fullName" },
    { id: "3", name: "email", type: "email" },
    { id: "4", name: "rating", type: "amount" },
    { id: "5", name: "comment", type: "jobTitle" },
    { id: "6", name: "verified", type: "boolean" },
  ],
  custom: [
    { id: "1", name: "id", type: "uuid" },
    { id: "2", name: "field_1", type: "fullName" },
    { id: "3", name: "field_2", type: "email" },
  ],
};

export const AD_CONFIG = {
  enabled: true,
  icon: "bolt",
  title: "DevPro Suite",
  description: "API mocking, schema generation & live testing for dev teams.",
  ctaText: "Start free trial",
  ctaUrl: "#",
};
