export const THEME_VARS = {
  light: {
    bg: "bg-[#fafafa]",
    text: "text-[#1a1a1a]",
    headerBg: "glass-light border-[#e0e0e0]/50",
    panelBg: "bg-[#ffffff] border-[#e0e0e0]",
    cardBg: "bg-[#ffffff] border-[#e0e0e0]",
    inputBg: "bg-[#f5f5f5] border-[#e0e0e0]",
    mutedText: "text-[#555555]",
    mutedText2: "text-[#888888]",
    hoverBorder: "hover:border-[#cccccc]",
    activeBtn: "bg-[#fff0f0] border-[#e0d0d0] text-[#c53a3a]",
    inactiveBtn: "bg-white border-[#e0e0e0] text-[#555555] hover:text-[#1a1a1a] hover:border-[#cccccc]",
    codeBg: "bg-[#f5f5f5] border-[#e0e0e0]",
  },
  dark: {
    bg: "bg-[#050505]",
    text: "text-[#c8c8c8]",
    headerBg: "glass border-[#1a1a1a]/50",
    panelBg: "bg-[#0a0a0a] border-[#1a1a1a]",
    cardBg: "bg-[#0a0a0a] border-[#1a1a1a]",
    inputBg: "bg-[#050505] border-[#1a1a1a]",
    mutedText: "text-[#555555]",
    mutedText2: "text-[#555555]",
    hoverBorder: "hover:border-[#2a2a2a]",
    activeBtn: "bg-[rgba(255,107,107,0.08)] border-[rgba(255,107,107,0.2)] text-[#FF6B6B]",
    inactiveBtn: "bg-[#0a0a0a] border-[#1a1a1a] text-[#555555] hover:text-[#888888] hover:border-[#2a2a2a]",
    codeBg: "bg-[#0a0a0a] border-[#1a1a1a]",
  },
};

export const DATA_TYPE_PRESETS = {
  users: [
    { id: "1", name: "id", type: "uuid" },
    { id: "2", name: "first_name", type: "fullName" },
    { id: "3", name: "last_name", type: "fullName" },
    { id: "4", name: "email", type: "email" },
    { id: "5", name: "age", type: "amount" },
    { id: "6", name: "phone", type: "phone" },
    { id: "7", name: "city", type: "fullName" },
    { id: "8", name: "state", type: "fullName" },
    { id: "9", name: "created_at", type: "email" },
  ],
  products: [
    { id: "1", name: "id", type: "uuid" },
    { id: "2", name: "title", type: "fullName" },
    { id: "3", name: "price", type: "amount" },
    { id: "4", name: "in_stock", type: "boolean" },
    { id: "5", name: "company", type: "company" },
  ],
  orders: [
    { id: "1", name: "id", type: "uuid" },
    { id: "2", name: "customer", type: "fullName" },
    { id: "3", name: "email", type: "email" },
    { id: "4", name: "amount", type: "amount" },
    { id: "5", name: "status", type: "boolean" },
  ],
  addresses: [
    { id: "1", name: "id", type: "uuid" },
    { id: "2", name: "full_name", type: "fullName" },
    { id: "3", name: "street", type: "fullName" },
    { id: "4", name: "city", type: "fullName" },
    { id: "5", name: "state", type: "fullName" },
    { id: "6", name: "phone", type: "phone" },
  ],
  transactions: [
    { id: "1", name: "id", type: "uuid" },
    { id: "2", name: "amount", type: "amount" },
    { id: "3", name: "currency", type: "fullName" },
    { id: "4", name: "status", type: "boolean" },
    { id: "5", name: "description", type: "jobTitle" },
    { id: "6", name: "created_at", type: "email" },
  ],
  posts: [
    { id: "1", name: "id", type: "uuid" },
    { id: "2", name: "title", type: "jobTitle" },
    { id: "3", name: "author", type: "fullName" },
    { id: "4", name: "email", type: "email" },
    { id: "5", name: "likes", type: "amount" },
    { id: "6", name: "published", type: "boolean" },
  ],
  employees: [
    { id: "1", name: "id", type: "uuid" },
    { id: "2", name: "full_name", type: "fullName" },
    { id: "3", name: "email", type: "email" },
    { id: "4", name: "job_title", type: "jobTitle" },
    { id: "5", name: "company", type: "company" },
    { id: "6", name: "phone", type: "phone" },
    { id: "7", name: "salary", type: "amount" },
  ],
  invoices: [
    { id: "1", name: "id", type: "uuid" },
    { id: "2", name: "customer", type: "fullName" },
    { id: "3", name: "email", type: "email" },
    { id: "4", name: "amount", type: "amount" },
    { id: "5", name: "company", type: "company" },
    { id: "6", name: "paid", type: "boolean" },
  ],
  reviews: [
    { id: "1", name: "id", type: "uuid" },
    { id: "2", name: "reviewer", type: "fullName" },
    { id: "3", name: "email", type: "email" },
    { id: "4", name: "rating", type: "amount" },
    { id: "5", name: "comment", type: "jobTitle" },
    { id: "6", name: "verified", type: "boolean" },
  ],
  custom: [
    { id: "1", name: "id", type: "uuid" },
    { id: "2", name: "field_1", type: "fullName" },
    { id: "3", name: "field_2", type: "email" },
  ],
};

export const AD_CONFIG = {
  enabled: true,
  icon: "bolt",
  title: "DevPro Suite",
  description: "API mocking, schema generation & live testing for dev teams.",
  ctaText: "Start free trial",
  ctaUrl: "#",
};

export const TOOL_SEO = {
  home: {
    title: "DevClat | Privacy-First Developer Toolkit",
    description: "Free, 100% private client-side developer toolkit. 21+ tools including Mock Data Generator, CSS to Tailwind Converter, JSON Formatter, and more.",
    keywords: "developer tools, free dev tools, frontend tools, client side tools, browser based developer tools, offline developer utilities",
    slug: "",
  },
  generator: {
    title: "Free JSON Dummy Data Generator | DevClat",
    description: "Generate custom, realistic fake JSON data payloads instantly. 10 presets, custom schemas, faker.js powered. 100% client-side and private.",
    keywords: "json dummy data generator, fake data generator, mock data generator, test data generator, json generator, generate fake json, create test data json, fake api response generator, json placeholder data",
    slug: "generator",
  },
  "json-formatter": {
    title: "JSON Formatter & Validator Online | DevClat",
    description: "Paste broken or minified JSON and get instant pretty-print, validation, and error line highlighting. Collapsible tree view included.",
    keywords: "json formatter online, json validator, pretty print json, json minifier, format json online, json lint, validate json, fix json errors, json beautifier, json pretty print online",
    slug: "json-formatter",
  },
  "text-diff": {
    title: "Text Diff Tool — Compare Text Side by Side | DevClat",
    description: "Paste two texts and instantly see line-level and word-level differences with git-diff style highlighting. Unified, split, and words modes.",
    keywords: "text diff tool, compare text online, diff checker, code diff tool, text comparison tool, compare two texts, find differences in text, side by side text compare, git diff online",
    slug: "text-diff",
  },
  "regex-tester": {
    title: "Regex Tester — Test Regular Expressions Online | DevClat",
    description: "Type a regex pattern and see matches highlighted in real-time. Capture groups, flag toggles (g, i, m, s, u), and instant feedback.",
    keywords: "regex tester online, regular expression validator, regex test tool, regex checker, test regex pattern, regex match highlighter, regex playground, regular expression online tester",
    slug: "regex-tester",
  },
  "css-converter": {
    title: "CSS to Tailwind CSS Converter Online | DevClat",
    description: "Convert raw CSS rules into clean Tailwind utility classes instantly. 200+ property mappings, dark mode, arbitrary values, color resolution.",
    keywords: "css to tailwind converter, tailwind css converter, convert css to tailwind, tailwind to css, css to tailwind online, tailwind class generator, css to utility classes, tailwind css online converter",
    slug: "css-converter",
  },
  base64: {
    title: "Base64 Encoder & Decoder Online | DevClat",
    description: "Encode any string to Base64 or decode Base64 back to plain text. Full Unicode support, real-time conversion, one-click copy.",
    keywords: "base64 encoder decoder, base64 encode online, base64 decode online, base64 converter, encode to base64, decode base64 string, base64 tool, base64 online decoder",
    slug: "base64",
  },
  "url-encoder": {
    title: "URL Encoder & Decoder Online | DevClat",
    description: "Encode special characters in URLs for safe transmission or decode percent-encoded strings back to readable text. Handles query params and paths.",
    keywords: "url encoder online, url decoder, percent encoding, encode url, decode url, url encode decode tool, uri encoder, url special characters encoder",
    slug: "url-encoder",
  },
  "jwt-decoder": {
    title: "JWT Token Decoder — Inspect JSON Web Tokens | DevClat",
    description: "Paste any JWT and instantly decode the header, payload, and signature. Check expiration, algorithm, and claims. Nothing leaves your browser.",
    keywords: "jwt decoder, jwt token decoder, json web token decoder, jwt parser, decode jwt online, jwt token inspector, jwt payload decoder, check jwt expiration",
    slug: "jwt-decoder",
  },
  layout: {
    title: "Flexbox & CSS Grid Visual Playground | DevClat",
    description: "Drag and drop elements to build flexbox and grid layouts visually. See the Tailwind output update in real-time as you adjust gaps and alignment.",
    keywords: "flexbox playground, css grid playground, flexbox visualizer, grid layout builder, flexbox trainer, css grid visualizer, learn flexbox, learn css grid, flexbox grid playground online",
    slug: "layout",
  },
  gradient: {
    title: "CSS Gradient Generator — Linear, Radial & Conic | DevClat",
    description: "Build CSS gradients visually with draggable color stops, angle control, and live preview. Copy the ready-to-use CSS code instantly.",
    keywords: "css gradient generator, gradient builder, linear gradient generator, radial gradient, conic gradient, css gradient maker, gradient color stops, create css gradient online",
    slug: "gradient",
  },
  "box-shadow": {
    title: "CSS Box Shadow Generator — Multi-Layer Visual Tool | DevClat",
    description: "Create complex CSS box shadows with multiple layers, inset mode, blur, spread, and offset. Live preview with copy-ready CSS output.",
    keywords: "box shadow generator, css shadow builder, box shadow css, css box shadow generator, create box shadow, shadow css generator, multi layer box shadow, inset shadow css",
    slug: "box-shadow",
  },
  "qr-code": {
    title: "Free QR Code Generator — Download PNG Instantly | DevClat",
    description: "Enter any text or URL and generate a downloadable QR code as a PNG image. Canvas-based rendering, no watermarks, no sign-up required.",
    keywords: "qr code generator free, qr code maker, create qr code online, qr code download png, url to qr code, text to qr code, free qr code generator no signup, qr code image generator",
    slug: "qr-code",
  },
  password: {
    title: "Strong Password Generator — Cryptographically Secure | DevClat",
    description: "Generate unbreakable passwords with configurable length, uppercase, lowercase, numbers, and symbols. Includes real-time strength meter.",
    keywords: "password generator strong, secure password generator, random password generator, create strong password, password strength checker, generate secure password online, password creator tool",
    slug: "password",
  },
  uuid: {
    title: "UUID v4 Generator — Batch Generate Up to 100 | DevClat",
    description: "Generate UUID v4 identifiers in standard (hyphenated) or compact format. Batch generate up to 100 at once with one click.",
    keywords: "uuid generator v4, generate uuid online, create uuid, random uuid generator, uuid v4 generator, batch uuid generator, unique identifier generator, uuid creator",
    slug: "uuid",
  },
  timestamp: {
    title: "Unix Timestamp Converter — Epoch to Date | DevClat",
    description: "Convert Unix timestamps to human-readable dates and back. Supports seconds and milliseconds, ISO 8601, and custom date formats.",
    keywords: "unix timestamp converter, epoch converter, timestamp to date, date to timestamp, unix time converter, epoch time converter, convert timestamp online, unix clock",
    slug: "timestamp",
  },
  lorem: {
    title: "Lorem Ipsum Generator — Custom Paragraph Count | DevClat",
    description: "Generate classic lorem ipsum placeholder text with your choice of paragraph count. Perfect for mockups, wireframes, and design prototypes.",
    keywords: "lorem ipsum generator, placeholder text generator, dummy text generator, lorem ipsum text, generate lorem ipsum, fake content generator, placeholder text for design",
    slug: "lorem",
  },
  tokenizer: {
    title: "LLM Token Counter — Count Tokens, Words & Characters | DevClat",
    description: "Count tokens, words, characters, and lines in any text. Visual token breakdown shows exactly how your text gets tokenized for LLM limits.",
    keywords: "llm token counter, token counter, count tokens online, word counter, character counter, tokenizer tool, gpt token counter, text token counter, how many tokens in text",
    slug: "tokenizer",
  },
  "html-preview": {
    title: "Live HTML Preview Editor — Code & See Results | DevClat",
    description: "Write HTML, CSS, and JavaScript in a side-by-side editor with instant live preview. Full-page preview mode and syntax highlighting included.",
    keywords: "html preview editor, live html editor, online code editor, html css js editor, sandbox html editor, html playground, code and preview html, live code editor online",
    slug: "html-preview",
  },
  markdown: {
    title: "Markdown Preview Editor — Live Rendered Output | DevClat",
    description: "Write Markdown on the left and see the rendered HTML output update in real-time. Supports headings, tables, code blocks, links, and images.",
    keywords: "markdown preview editor, markdown editor online, markdown to html, live markdown preview, markdown renderer, write markdown online, markdown live editor, markdown playground",
    slug: "markdown",
  },
  "color-contrast": {
    title: "WCAG Color Contrast Checker — Accessibility Audit | DevClat",
    description: "Check foreground and background color combinations against WCAG 2.1 AA and AAA contrast ratio requirements. Instant pass/fail results.",
    keywords: "color contrast checker, wcag contrast checker, accessibility contrast tool, color accessibility checker, wcag aa contrast ratio, contrast ratio calculator, color contrast ratio checker, wcag compliance checker",
    slug: "color-contrast",
  },
  "css-minifier": {
    title: "CSS Minifier & Compressor — Reduce File Size | DevClat",
    description: "Paste your CSS and instantly compress it by stripping whitespace, comments, and redundant characters. Shows original vs minified size comparison.",
    keywords: "css minifier, minify css online, css compressor, compress css, reduce css file size, css optimizer, minify css code, css minifier tool, shrink css file",
    slug: "css-minifier",
  },
};
