export const THEME_VARS = {
  light: {
    bg: "bg-[#f7f6f3]",
    text: "text-[#1a1d26]",
    headerBg: "bg-[#f7f6f3]/80 border-[#e2e0da]",
    panelBg: "bg-[#f7f6f3] border-[#e2e0da]",
    cardBg: "bg-white border-[#e2e0da]",
    inputBg: "bg-[#f0efe9] border-[#e2e0da]",
    mutedText: "text-[#5a5f6e]",
    mutedText2: "text-[#9ca3b0]",
    hoverBorder: "hover:border-[#d0cec8]",
    activeBtn: "bg-[#fff8ed] border-[#f0dfc0] text-[#c87d0a]",
    inactiveBtn: "bg-white border-[#e2e0da] text-[#5a5f6e] hover:text-[#1a1d26] hover:border-[#d0cec8]",
    codeBg: "bg-[#f0efe9] border-[#e2e0da]",
  },
  dark: {
    bg: "bg-[#0c0e14]",
    text: "text-[#c8ccd4]",
    headerBg: "bg-[#0c0e14]/80 border-[#1c2030]",
    panelBg: "bg-[#12151e] border-[#1c2030]",
    cardBg: "bg-[#12151e] border-[#1c2030]",
    inputBg: "bg-[#0c0e14] border-[#1c2030]",
    mutedText: "text-[#505868]",
    mutedText2: "text-[#505868]",
    hoverBorder: "hover:border-[#2a3045]",
    activeBtn: "bg-[rgba(240,165,0,0.08)] border-[rgba(240,165,0,0.2)] text-[#f0a500]",
    inactiveBtn: "bg-[#12151e] border-[#1c2030] text-[#505868] hover:text-[#8891a4] hover:border-[#2a3045]",
    codeBg: "bg-[#0a0c12] border-[#1c2030]",
  },
};

export const DATA_TYPE_PRESETS = {
  users: [
    { id: "1", name: "id", type: "uuid" },
    { id: "2", name: "first_name", type: "fullName" },
    { id: "3", name: "last_name", type: "fullName" },
    { id: "4", name: "email", type: "email" },
    { id: "5", name: "age", type: "amount" },
    { id: "6", name: "phone", type: "phone" },
    { id: "7", name: "city", type: "fullName" },
    { id: "8", name: "state", type: "fullName" },
    { id: "9", name: "created_at", type: "email" },
  ],
  products: [
    { id: "1", name: "id", type: "uuid" },
    { id: "2", name: "title", type: "fullName" },
    { id: "3", name: "price", type: "amount" },
    { id: "4", name: "in_stock", type: "boolean" },
    { id: "5", name: "company", type: "company" },
  ],
  orders: [
    { id: "1", name: "id", type: "uuid" },
    { id: "2", name: "customer", type: "fullName" },
    { id: "3", name: "email", type: "email" },
    { id: "4", name: "amount", type: "amount" },
    { id: "5", name: "status", type: "boolean" },
  ],
  addresses: [
    { id: "1", name: "id", type: "uuid" },
    { id: "2", name: "full_name", type: "fullName" },
    { id: "3", name: "street", type: "fullName" },
    { id: "4", name: "city", type: "fullName" },
    { id: "5", name: "state", type: "fullName" },
    { id: "6", name: "phone", type: "phone" },
  ],
  transactions: [
    { id: "1", name: "id", type: "uuid" },
    { id: "2", name: "amount", type: "amount" },
    { id: "3", name: "currency", type: "fullName" },
    { id: "4", name: "status", type: "boolean" },
    { id: "5", name: "description", type: "jobTitle" },
    { id: "6", name: "created_at", type: "email" },
  ],
  posts: [
    { id: "1", name: "id", type: "uuid" },
    { id: "2", name: "title", type: "jobTitle" },
    { id: "3", name: "author", type: "fullName" },
    { id: "4", name: "email", type: "email" },
    { id: "5", name: "likes", type: "amount" },
    { id: "6", name: "published", type: "boolean" },
  ],
  employees: [
    { id: "1", name: "id", type: "uuid" },
    { id: "2", name: "full_name", type: "fullName" },
    { id: "3", name: "email", type: "email" },
    { id: "4", name: "job_title", type: "jobTitle" },
    { id: "5", name: "company", type: "company" },
    { id: "6", name: "phone", type: "phone" },
    { id: "7", name: "salary", type: "amount" },
  ],
  invoices: [
    { id: "1", name: "id", type: "uuid" },
    { id: "2", name: "customer", type: "fullName" },
    { id: "3", name: "email", type: "email" },
    { id: "4", name: "amount", type: "amount" },
    { id: "5", name: "company", type: "company" },
    { id: "6", name: "paid", type: "boolean" },
  ],
  reviews: [
    { id: "1", name: "id", type: "uuid" },
    { id: "2", name: "reviewer", type: "fullName" },
    { id: "3", name: "email", type: "email" },
    { id: "4", name: "rating", type: "amount" },
    { id: "5", name: "comment", type: "jobTitle" },
    { id: "6", name: "verified", type: "boolean" },
  ],
  custom: [
    { id: "1", name: "id", type: "uuid" },
    { id: "2", name: "field_1", type: "fullName" },
    { id: "3", name: "field_2", type: "email" },
  ],
};

export const AD_CONFIG = {
  enabled: true,
  icon: "bolt",
  title: "DevPro Suite",
  description: "API mocking, schema generation & live testing for dev teams.",
  ctaText: "Start free trial",
  ctaUrl: "#",
};
